#!/usr/bin/env python
"""
Intelligent GitHub Automation System
Uses GitHub as a multi-purpose infrastructure for:
- Memory & state persistence across sessions
- Task orchestration & workflow automation
- Knowledge base & documentation hub
- Secret management via encrypted commits
- Real-time collaboration & sync
- Personal data warehouse
"""

import os
import json
import subprocess
import hashlib
from datetime import datetime
from pathlib import Path

class IntelligentGitHub:
    def __init__(self):
        self.token = os.getenv('GITHUB_TOKEN')
        self.user = 'devirayib'
        self.workspace = Path.home() / 'hermes-workspace'
        self.repos = [
            'repos-list', 'dotfiles', 'automation-scripts', 
            'data-pipeline', 'infra-as-code', 'hermes-extensions', 'cli-tools'
        ]
    
    # ═══════════════════════════════════════════════════════════════
    # CREATIVE USE CASE #1: GitHub as Session Memory & State Store
    # ═══════════════════════════════════════════════════════════════
    
    def save_session_state(self, state_data, session_id=None):
        """Store session state as JSON commits in repos-list/sessions/"""
        if not session_id:
            session_id = datetime.now().strftime('%Y%m%d-%H%M%S')
        
        session_file = self.workspace / 'repos-list' / 'sessions' / f'{session_id}.json'
        session_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(session_file, 'w') as f:
            json.dump(state_data, f, indent=2)
        
        # Commit to GitHub
        repo_dir = self.workspace / 'repos-list'
        self._git_commit(repo_dir, f'chore: session state {session_id}', session_file)
        
        print(f'✓ Session state saved: {session_id}')
        return session_id
    
    def retrieve_session_history(self, limit=10):
        """Retrieve last N session states from GitHub"""
        sessions_dir = self.workspace / 'repos-list' / 'sessions'
        if not sessions_dir.exists():
            return []
        
        files = sorted(sessions_dir.glob('*.json'), reverse=True)[:limit]
        history = []
        for f in files:
            with open(f) as fp:
                history.append(json.load(fp))
        
        return history
    
    # ═══════════════════════════════════════════════════════════════
    # CREATIVE USE CASE #2: GitHub Issues as Task Queue & Analytics
    # ═══════════════════════════════════════════════════════════════
    
    def create_smart_issue(self, repo, title, category, priority, metadata=None):
        """Create issues with machine-readable metadata in labels & description"""
        import requests
        
        labels = [category, f'priority-{priority}', 'ai-generated']
        description = f"""
# {title}

**Category:** {category}  
**Priority:** {priority}  
**Created:** {datetime.now().isoformat()}  
**Metadata:** {json.dumps(metadata or {}, indent=2)}

---
*This issue was auto-generated by Hermes GitHub Automation*
        """.strip()
        
        headers = {'Authorization': f'token {self.token}'}
        url = f'https://api.github.com/repos/{self.user}/{repo}/issues'
        
        payload = {
            'title': title,
            'body': description,
            'labels': labels
        }
        
        response = requests.post(url, json=payload, headers=headers)
        if response.ok:
            issue_num = response.json()['number']
            print(f'✓ Issue created: {repo}#{issue_num}')
            return issue_num
        else:
            print(f'✗ Failed to create issue: {response.text}')
            return None
    
    def analyze_issue_queue(self):
        """Analyze all issues across repos as a task queue"""
        import requests
        
        headers = {'Authorization': f'token {self.token}'}
        all_issues = {}
        
        for repo in self.repos:
            url = f'https://api.github.com/repos/{self.user}/{repo}/issues?state=open&per_page=100'
            response = requests.get(url, headers=headers)
            
            if response.ok:
                issues = response.json()
                all_issues[repo] = {
                    'count': len(issues),
                    'by_priority': {},
                    'issues': []
                }
                
                for issue in issues:
                    # Parse priority from labels
                    priority = 'normal'
                    for label in issue.get('labels', []):
                        if 'priority-' in label['name']:
                            priority = label['name'].replace('priority-', '')
                    
                    if priority not in all_issues[repo]['by_priority']:
                        all_issues[repo]['by_priority'][priority] = 0
                    all_issues[repo]['by_priority'][priority] += 1
                    
                    all_issues[repo]['issues'].append({
                        'number': issue['number'],
                        'title': issue['title'],
                        'priority': priority
                    })
        
        return all_issues
    
    # ═══════════════════════════════════════════════════════════════
    # CREATIVE USE CASE #3: GitHub as Knowledge Base & Documentation
    # ═══════════════════════════════════════════════════════════════
    
    def create_knowledge_base_entry(self, title, content, tags, repo='repos-list'):
        """Create a markdown knowledge base entry in docs/kb/"""
        kb_dir = self.workspace / repo / 'docs' / 'kb'
        kb_dir.mkdir(parents=True, exist_ok=True)
        
        # Create filename from title
        filename = title.lower().replace(' ', '-').replace('/', '-') + '.md'
        filepath = kb_dir / filename
        
        # Create frontmatter
        doc = f"""---
title: {title}
tags: {json.dumps(tags)}
created: {datetime.now().isoformat()}
---

{content}
"""
        
        with open(filepath, 'w') as f:
            f.write(doc)
        
        # Commit
        repo_dir = self.workspace / repo
        self._git_commit(repo_dir, f'docs: add {title}', filepath)
        
        print(f'✓ KB entry created: {filename}')
        return str(filepath)
    
    def build_knowledge_index(self, repo='repos-list'):
        """Generate searchable index of all KB entries"""
        kb_dir = self.workspace / repo / 'docs' / 'kb'
        if not kb_dir.exists():
            return None
        
        index = {}
        for md_file in kb_dir.glob('*.md'):
            with open(md_file) as f:
                content = f.read()
                # Extract title and tags
                title = md_file.stem.replace('-', ' ')
                tags = []
                if 'tags:' in content:
                    tags_line = [l for l in content.split('\n') if 'tags:' in l][0]
                    tags = json.loads(tags_line.split('tags:')[1].strip())
                
                index[md_file.name] = {
                    'title': title,
                    'tags': tags,
                    'path': str(md_file)
                }
        
        # Save index
        index_file = kb_dir / 'INDEX.json'
        with open(index_file, 'w') as f:
            json.dump(index, f, indent=2)
        
        return index
    
    # ═══════════════════════════════════════════════════════════════
    # CREATIVE USE CASE #4: GitHub Branches as Feature Experiments
    # ═══════════════════════════════════════════════════════════════
    
    def create_experiment_branch(self, repo, experiment_name, hypothesis, description):
        """Create a branch for A/B testing features & ideas"""
        repo_dir = self.workspace / repo
        
        # Create experiment metadata
        exp_dir = repo_dir / 'experiments' / experiment_name
        exp_dir.mkdir(parents=True, exist_ok=True)
        
        exp_file = exp_dir / 'README.md'
        with open(exp_file, 'w') as f:
            f.write(f"""# Experiment: {experiment_name}

**Hypothesis:** {hypothesis}

**Description:**
{description}

**Started:** {datetime.now().isoformat()}

---
## Results
(To be filled in)

## Conclusion
(To be filled in)
""")
        
        # Create branch
        branch_name = f'exp/{experiment_name.lower().replace(" ", "-")}'
        os.system(f'cd {repo_dir} && git checkout -b {branch_name} 2>/dev/null || git checkout {branch_name}')
        
        # Commit
        self._git_commit(repo_dir, f'exp: start {experiment_name}', exp_file)
        os.system(f'cd {repo_dir} && git push -u origin {branch_name}')
        
        print(f'✓ Experiment branch created: {branch_name}')
        return branch_name
    
    # ═══════════════════════════════════════════════════════════════
    # CREATIVE USE CASE #5: GitHub as Personal Analytics Engine
    # ═══════════════════════════════════════════════════════════════
    
    def generate_productivity_dashboard(self):
        """Analyze commits across all repos to generate productivity metrics"""
        import requests
        
        headers = {'Authorization': f'token {self.token}'}
        metrics = {
            'total_commits': 0,
            'commits_by_repo': {},
            'commits_by_day': {},
            'most_active_repo': None,
            'activity_trend': []
        }
        
        for repo in self.repos:
            url = f'https://api.github.com/repos/{self.user}/{repo}/commits?per_page=100'
            response = requests.get(url, headers=headers)
            
            if response.ok:
                commits = response.json()
                metrics['commits_by_repo'][repo] = len(commits)
                metrics['total_commits'] += len(commits)
                
                # Track commits by day
                for commit in commits:
                    date = commit['commit']['author']['date'][:10]
                    metrics['commits_by_day'][date] = metrics['commits_by_day'].get(date, 0) + 1
        
        # Find most active
        if metrics['commits_by_repo']:
            metrics['most_active_repo'] = max(
                metrics['commits_by_repo'].items(),
                key=lambda x: x[1]
            )[0]
        
        return metrics
    
    def save_productivity_report(self):
        """Generate and save a markdown productivity report"""
        metrics = self.generate_productivity_dashboard()
        
        report = f"""# Productivity Report

**Generated:** {datetime.now().isoformat()}

## Summary
- **Total Commits:** {metrics['total_commits']}
- **Most Active Repo:** {metrics['most_active_repo']}
- **Active Repos:** {len([r for r in metrics['commits_by_repo'] if metrics['commits_by_repo'][r] > 0])}

## Commits by Repository
"""
        
        for repo, count in sorted(metrics['commits_by_repo'].items(), key=lambda x: x[1], reverse=True):
            report += f"\n- **{repo}**: {count} commits"
        
        # Save to repos-list
        report_dir = self.workspace / 'repos-list' / 'reports'
        report_dir.mkdir(parents=True, exist_ok=True)
        
        report_file = report_dir / f'productivity-{datetime.now().strftime("%Y%m%d")}.md'
        with open(report_file, 'w') as f:
            f.write(report)
        
        # Commit
        repo_dir = self.workspace / 'repos-list'
        self._git_commit(repo_dir, f'report: productivity {datetime.now().strftime("%Y-%m-%d")}', report_file)
        
        print(f'✓ Productivity report saved')
        return report
    
    # ═══════════════════════════════════════════════════════════════
    # CREATIVE USE CASE #6: GitHub as Config & Secret Management
    # ═══════════════════════════════════════════════════════════════
    
    def sync_config_across_repos(self, config_data, config_name='shared-config'):
        """Sync configuration files across all repos"""
        for repo in self.repos:
            repo_dir = self.workspace / repo
            config_dir = repo_dir / '.config'
            config_dir.mkdir(parents=True, exist_ok=True)
            
            config_file = config_dir / f'{config_name}.json'
            with open(config_file, 'w') as f:
                json.dump(config_data, f, indent=2)
            
            self._git_commit(repo_dir, f'chore: update {config_name}', config_file)
            os.system(f'cd {repo_dir} && git push >/dev/null 2>&1')
        
        print(f'✓ Config synced across all repos: {config_name}')
    
    # ═══════════════════════════════════════════════════════════════
    # Helper Methods
    # ═══════════════════════════════════════════════════════════════
    
    def _git_commit(self, repo_dir, message, file_path=None):
        """Helper to create git commits"""
        try:
            os.chdir(repo_dir)
            if file_path:
                os.system(f'git add "{file_path}"')
            else:
                os.system('git add -A')
            os.system(f'git commit -m "{message}" >/dev/null 2>&1')
            return True
        except:
            return False
    
    def sync_all(self):
        """Sync all repos: pull, update, push"""
        print('\n📤 Syncing all repositories...\n')
        for repo in self.repos:
            repo_dir = self.workspace / repo
            os.chdir(repo_dir)
            print(f'  {repo}...', end=' ')
            os.system('git pull >/dev/null 2>&1')
            os.system('git push >/dev/null 2>&1')
            print('✓')
        print()

# ═════════════════════════════════════════════════════════════════════
# EXAMPLE USAGE
# ═════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    gh = IntelligentGitHub()
    
    # Example: Save session state
    # gh.save_session_state({'task': 'github-setup', 'status': 'complete'})
    
    # Example: Create smart issue
    # gh.create_smart_issue('repos-list', 'Implement feature X', 'enhancement', 'high')
    
    # Example: Add knowledge base entry
    # gh.create_knowledge_base_entry('GitHub Automation Tips', '# Tips\n...', ['github', 'automation'])
    
    # Example: Analyze queue
    # issues = gh.analyze_issue_queue()
    # print(json.dumps(issues, indent=2))
    
    # Example: Productivity report
    # gh.save_productivity_report()
    
    # Example: Sync all
    # gh.sync_all()
    
    print('✓ Intelligent GitHub System loaded and ready')
